//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class LateFees
    {
        public int Id { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<System.DateTime> BuyingDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> BookRecordsId { get; set; }
    
        public virtual BookRecords BookRecords { get; set; }
        public virtual Members Members { get; set; }
    }
}
